[backdrop]
blur_intensity = 0.40999999083578587
tint_intensity = 0.0

[bar]
order = [ "bar", "clock_bar", "text" ]

    [bar.bar]
    capsule = true
    capsule_padding = 5.0
    capsule_radius = 4
    capsule_thickness = 0.90999998338520527
    center = [ "group:g1" ]
    enabled = false
    end = [ "group:g5", "group:g3" ]
    margin_ends = 0
    padding = 10
    panel_overlap = 0
    radius = 0
    show_on_workspace_switch = false
    start = [ "group:g4" ]
    thickness = 31

        [[bar.bar.capsule_group]]
        border = "primary"
        enabled = true
        fill = "on_secondary"
        id = "g1"
        members = [ "clipboard", "notes_3", "clock", "wallpaper", "mpvpaper" ]
        opacity = 1.0
        padding = 14.0
        radius = 4.0

        [[bar.bar.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "wallpaper", "bluetooth", "settings", "volume", "clipboard", "session" ]
        opacity = 1.0
        padding = 11.0
        radius = 4.0

        [[bar.bar.capsule_group]]
        border = "primary"
        enabled = true
        fill = "on_secondary"
        id = "g3"
        members = [ "session", "settings" ]
        opacity = 1.0
        padding = 9.0
        radius = 4.0

        [[bar.bar.capsule_group]]
        border = "primary"
        enabled = true
        fill = "on_secondary"
        id = "g4"
        members = [ "media", "sysmon" ]
        opacity = 1.0
        padding = 8.0
        radius = 4.0

        [[bar.bar.capsule_group]]
        border = "primary"
        enabled = true
        fill = "on_secondary"
        id = "g5"
        members = [ "weather", "recorder_4", "volume" ]
        opacity = 1.0
        padding = 8.0
        radius = 4.0

    [bar.clock_bar]
    border = "on_primary"
    capsule_padding = 1.0
    contact_shadow = true
    end = []
    margin_ends = 922
    padding = 15
    panel_overlap = 0
    radius = 0
    radius_bottom_left = 31
    radius_bottom_right = 34
    scale = 0.65000000223517418
    start = []
    thickness = 24

    [bar.text]
    auto_hide = true
    border = "primary"
    capsule = true
    capsule_radius = 4
    center = [ "settings", "output_volume", "media", "weather", "wallpaper", "recorder_6", "clipboard", "notes_5", "session" ]
    enabled = true
    end = []
    margin_ends = 584
    position = "bottom"
    radius_bottom_left = 0
    radius_bottom_right = 0
    scale = 1.2500000111758709
    show_on_workspace_switch = false
    start = []
    thickness = 40

[control_center]
sidebar = "none"
sidebar_section = "none"

[dock]
auto_hide = true
background_opacity = 0.99999997764825821
cross_axis_padding = 0
icon_size = 40
inactive_opacity = 0.99999997764825821
main_axis_padding = 7
margin_ends = 82
pinned = [ "zen", "spotify", "org.gnome.Nautilus", "kitty", "com.stremio.stremio", "io.github.nirimod" ]
shadow = false
show_dots = true

[keybinds]
validate = [ "Return", "KP_Enter", "space" ]

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.0

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@winit", "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 957.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 70.0
    box_width = 400.0
    cx = 921.0
    cy = 777.0
    output = "winit"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[nightlight]
enabled = true

[osd]
background_opacity = 0.0

[plugin_settings."noctalia/mpvpaper"]
video_directory = "/home/za/Downloads"

[plugin_settings."noctalia/screen_recorder"]
frame_rate = 165
quality = "ultra"

[plugins]
enabled = [ "noctalia/notes", "noctalia/screen_recorder", "noctalia/timer", "noctalia/translator", "noctalia/mpvpaper" ]

[shell]
corner_radius_scale = 1.4000000208616257
font_family = "Cantarell"
telemetry_enabled = false

    [shell.animation]
    speed = 0.7500000111758709

    [shell.launcher]
    categories = false

    [shell.panel]
    clipboard_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_wallpaper = true
    polkit_placement = "attached"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screen_corners]
    size = 64

    [shell.shadow]
    alpha = 0.99999997764825821
    direction = "center"

[theme]
builtin = "Noctalia"
community_palette = "Doomed"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "faithful"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "ghostty", "kitty", "niri", "sway" ]
    community_ids = [ "spicetify", "neovim", "vscode", "obs", "opencode" ]

[wallpaper]
directory = "/home/za/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/za/Pictures/Wallpapers/wallhaven-5gym13_3840x2160.png"

    [wallpaper.last]
    path = "/home/za/Pictures/Wallpapers/wallhaven-5gym13_3840x2160.png"

    [wallpaper.monitors.DP-1]
    path = "/home/za/Pictures/Wallpapers/wallhaven-5gym13_3840x2160.png"

[widget.bluetooth]
enabled = true

[widget.clipboard]
capsule = true
capsule_opacity = 0.0
capsule_padding = 16
icon_color = "primary"

[widget.clock]
anchor = true
capsule_foreground = "primary"
capsule_opacity = 0.0
capsule_padding = 16
capsule_radius = 4
color = "primary"
enabled = true
font_family = "MesloLGL Nerd Font"
icon_color = "primary"
scale = 1.4500000000000002

[widget.control-center]
anchor = true
capsule = true
capsule_border = "on_secondary"
capsule_foreground = "surface_variant"
capsule_padding = 9
capsule_radius = 16
color = "on_secondary"
custom_image = "/usr/share/noctalia/assets/images/distros/arch.svg"
custom_image_colorize = true
scale = 1.1000000000000001

[widget.media]
art_size = 25
capsule = true
capsule_opacity = 0.0
capsule_padding = 15
enabled = true
hide_when_no_media = true
max_length = 40
min_length = 0

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.notes]
type = "noctalia/notes:notes"

[widget.notes_2]
type = "noctalia/notes:notes"

[widget.notes_3]
capsule = true
capsule_padding = 8
type = "noctalia/notes:notes"

[widget.notes_4]
type = "noctalia/notes:notes"

[widget.notes_5]
capsule = true
capsule_opacity = 0.0
capsule_padding = 16
color = "primary"
type = "noctalia/notes:notes"

[widget.output_volume]
capsule = true
capsule_opacity = 0.0
capsule_padding = 15
capsule_radius = 4
custom_image = "/home/za/Downloads/head.svg"
custom_image_colorize = true
icon_color = "primary"
scale = 1.1500000000000001
scroll_step = 6
show_label = false

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.recorder_2]
type = "noctalia/screen_recorder:recorder"

[widget.recorder_3]
capsule_padding = 9
type = "noctalia/screen_recorder:recorder"

[widget.recorder_4]
capsule_border = "primary"
type = "noctalia/screen_recorder:recorder"

[widget.recorder_5]
type = "noctalia/screen_recorder:recorder"

[widget.recorder_6]
capsule = true
capsule_opacity = 0.0
capsule_padding = 16
color = "primary"
scale = 1.1500000000000001
type = "noctalia/screen_recorder:recorder"

[widget.session]
capsule = true
capsule_opacity = 0.0
capsule_padding = 16
icon_color = "primary"

[widget.settings]
capsule = true
capsule_opacity = 0.02
capsule_padding = 16
capsule_radius = "auto"
color = "primary"
custom_image = "/usr/share/noctalia/assets/images/distros/arch.svg"
custom_image_colorize = true

[widget.sysmon]
capsule = true
show_label = false

[widget.volume]
capsule_radius = 4
show_label = false

[widget.wallpaper]
capsule = true
capsule_opacity = 0.0
capsule_padding = 16
capsule_radius = 4
color = "primary"

[widget.weather]
capsule = true
capsule_opacity = 0.0
capsule_padding = 16
color = "primary"
icon_color = "primary"
scale = 0.90000000000000002
show_condition = false

[widget.workspaces]
anchor = true
capsule = true
capsule_fill = "surface_variant"
capsule_opacity = 0.0
capsule_radius = 8
color = "on_surface"
