[config]

[templates.oh-my-posh]
input_path = "/home/za/.config/noctalia/oh-my-posh-atomic.template.json"
output_path = "/home/za/.cache/oh-my-posh/themes/atomic.omp.json"
post_hook = "python3 /home/za/.config/noctalia/patch-omp-theme.py --scheme /home/za/.cache/noctalia/predefined-scheme.json --output /home/za/.cache/oh-my-posh/themes/atomic.omp.json"

[templates.opencode]
input_path = "/home/za/.config/noctalia/opencode.template.json"
output_path = "/home/za/.config/opencode/themes/noctalia.json"
