palette = "noctalia"
add_newline = true
format = """
$cmd_duration $directory$git_branch
  $character"""

[fill]
symbol = '-'
style = 'fg:7'

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[ ](bold fg:2)"
error_symbol = "[ ](bold fg:1)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg: 5"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = " [](bold fg:5)[$symbol $branch(:$remote_branch)](fg:0 bg:5)[ ](bold fg:5)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold 1)"

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 ‍"
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](2)'
renamed = " ✍️ "
deleted = " 🗑 "

[hostname]
ssh_only = false
format =  "[•$hostname](bg:1 bold fg:0)[](bold fg:1)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed 2"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:2 fg:0"
style_root = "1 bold"
format = "[](bold fg:0)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = " "
read_only = "  "
style = "bg:4 fg:0"
truncation_length = 2
truncation_symbol = ".../"
format = '[](bold fg:4)[󰉋 → $path]($style)[](bold fg:4)'


[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[cmd_duration]
min_time = 0
format = '[](bold fg:3)[󰪢 $duration](bold bg:3 fg:0)[](bold fg:3)'

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#b5a895"
red       = "#cf767c"
green     = "#9aa887"
yellow    = "#e5c799"
cyan      = "#96b3aa"
magenta   = "#cbaba0"
white     = "#dcd8cd"
black     = "#231e1a"

# Extended palette (Catppuccin-compatible names)
rosewater = "#f0dbb7"
flamingo  = "#e09fa4"
pink      = "#dec7be"
mauve     = "#cbaba0"
maroon    = "#e09fa4"
peach     = "#f0dbb7"
teal      = "#96b3aa"
sky       = "#b1ccc4"
sapphire  = "#ccbfae"
lavender  = "#dec7be"

# Text shades
text      = "#dcd8cd"
subtext1  = "#dcd8cd"
subtext0  = "#3a3028"

# Surface shades
overlay2  = "#3a3028"
overlay1  = "#3a3028"
overlay0  = "#231e1a"
surface2  = "#231e1a"
surface1  = "#231e1a"
surface0  = "#161311"
base      = "#161311"
mantle    = "#161311"
crust     = "#161311"
# <<< NOCTALIA STARSHIP PALETTE <<<
